services:
  front_app:
    build: ./front_app
    ports:
      - "3000:3000"
    depends_on:
      - server_app
    restart: always


  server_app:
    build: ./server_app
    ports:
      - "3001:3001"
    depends_on:
        - mongo
    restart: always


  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
        - ./mongodb/data:/data/db