services:
  front_app:
    build: ./front_app
    ports:
      - "3000:3000"
    volumes:
      - ./front_app/docker.env:/front_app/.env
    depends_on:
      - server_app
    restart: always
    networks:
      - www_mmi

  server_app:
    build: ./server_app
    ports:
      - "3001:3001"
    volumes:
      - ./server_app/docker.env:/app/.env
    depends_on:
        - mongo
    restart: always
    networks:
      - www_mmi

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: www_mmi
    ports:
      - "27017:27017"
    volumes:
        - ./mongodb/data:/data/db
    networks:
      - www_mmi

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server_app
      - front_app
      - mongo
    networks:
      - www_mmi

networks:
  www_mmi: